// Usage: npx ts-node scripts/test-canonical-curl.ts
// This script tests that the canonical curl generated by normalizeSlackCurl matches the real curl's critical fields.

const { normalizeSlackCurl } = require("../lib/utils/normalize-slack-curl")

// Paste your working curl here (redact secrets if sharing)
const workingCurl = `curl 'https://urbankitchens.slack.com/api/emoji.adminList?_x_id=7ec08bbd-1747751651.513&slack_route=T0KV71EGN&_x_version_ts=noversion&fp=5c&_x_num_retries=0' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryfrnG03lNvmZYvVuk' \
  -b 'd-s=1713281859; b=.09d135ae70f5c638bcd26df652ab436b; utm=%7B%7D; _gcl_au=1.1.465713859.1747408281; OptanonConsent=isGpcEnabled=1&datestamp=Fri+May+16+2025+14%3A53%3A17+GMT-0400+(Eastern+Daylight+Time)&version=202402.1.0&groups=1%3A1%2C3%3A1%2C2%3A1%2C4%3A0&consentId=6eb84a58-b537-4cf0-be37-d8daed754577&hosts=; d=xoxd-hgLNkw5LPzfp7iilm7aAGoL6CEm5EsDRd2EK%2BprZyuy5p%2FujtUlE5bpyzmffcA%2Fv6bKX5KRzNhNUUtvt1o3a%2ByQzzcDxvvCBn1ObUBfbvjAZ%2BFdZiJQRj%2FRQ4JZerGiOQC6KHbT7LZfZSS%2BrNiBTP%2FD758fa3BlAwRbfRmZEDKOi0TSZ63j0mWhvWX7kDhf6ETBqzipOEw%3D%3D; x=09d135ae70f5c638bcd26df652ab436b.1747751640; PageCount=41' \
  -H 'dnt: 1' \
  -H 'origin: https://urbankitchens.slack.com' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'sec-ch-ua: "Not.A/Brand";v="99", "Chromium";v="136"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Mobile Safari/537.36' \
  --data-raw $'------WebKitFormBoundaryfrnG03lNvmZYvVuk\r\nContent-Disposition: form-data; name="token"\r\n\rxoxc-19993048566-1485274920231-7263455073525-54b90a11600ba25a1544841b6e319b0fbc85e5f8d2e38856fba0517eb5035f96\r\n------WebKitFormBoundaryfrnG03lNvmZYvVuk\r\nContent-Disposition: form-data; name="page"\r\n\r1\r\n------WebKitFormBoundaryfrnG03lNvmZYvVuk\r\nContent-Disposition: form-data; name="count"\r\n\r100\r\n------WebKitFormBoundaryfrnG03lNvmZYvVuk\r\nContent-Disposition: form-data; name="_x_reason"\r\n\rcustomize-emoji-new-query\r\n------WebKitFormBoundaryfrnG03lNvmZYvVuk\r\nContent-Disposition: form-data; name="_x_mode"\r\n\ronline\r\n------WebKitFormBoundaryfrnG03lNvmZYvVuk--\r\n'
`

console.log("Original curl:\n", workingCurl)

const canonicalCurl = normalizeSlackCurl(workingCurl)
console.log("\nCanonical curl:\n", canonicalCurl)

function assertContains(str: any, substr: any, label: any) {
  if (!str.includes(substr)) {
    console.error(`❌ Missing ${label}:`, substr)
    process.exit(1)
  } else {
    console.log(`✅ Found ${label}`)
  }
}

// Check critical fields
assertContains(canonicalCurl, "_x_id=7ec08bbd-1747751651.513", "_x_id")
assertContains(canonicalCurl, "slack_route=T0KV71EGN", "slack_route")
assertContains(canonicalCurl, "token=xoxc-", "token field")
assertContains(canonicalCurl, "--form page=1", "page field")
assertContains(canonicalCurl, "--form count=100", "count field")
assertContains(canonicalCurl, "--form _x_reason=customize-emoji-new-query", "_x_reason field")
assertContains(canonicalCurl, "--form _x_mode=online", "_x_mode field")
assertContains(canonicalCurl, "Cookie: d-s=", "cookie header")

console.log("\nAll critical fields found. Canonical curl matches expectations!\n")
